### ISSUE TITLE
Use spaces instead of tabs for indentation

### ISSUE THREAD

**Issue by medthehatta** [orokro/Classetta#1]
Throughout the generated code, tabs are used for indentation.  Please use spaces, because tabs are not displayed consistently between editors, and because they are indistinguishable from spaces except where they inexplicably break something.

Plus, in most editors, the default tabstop is too wide, so the code ends up super wide for no reason.

**Comment by orokro** [comment]
Good idea - everything is .replace(/\t/g, "&nbsp; (...)") now before it hits the DOM.
