### ISSUE TITLE
Perl: items in @ISA do not have associated use statements

### ISSUE THREAD

**Issue by medthehatta** [orokro/Classetta#11]
If you have

``` perl
our @ISA = qw(
    First
    Second
);
```

Then you should have also included the things that are inherited.  I.E.:

``` perl
use First;
use Second;

our @ISA = qw(
    First
    Second
);
```

**Comment by orokro** [comment]
Fixed... Not sure how I feel about this one, but since it already has "use strict" and "use warnings" I'll let it be for now.
