### ISSUE TITLE
For Perl, says doesn't support static members, but then lists members under a "Static Members" section

### ISSUE THREAD

**Issue by medthehatta** [orokro/Classetta#3]
At the top, it says:

"Warning! Perl doesn't support Static Members! Declaring as regular Members instead."

but then, when the members are actually defined, it says

"# Static Members"

The comment can probably be safely dropped.

**Comment by orokro** [comment]
So I assume:

# Static Members

my anInt = undef;
my aShort = 12300;

Is correct and instead I should remove the warning? Are these technically static / "class" members?

**Comment by medthehatta** [comment]
:recycle: Dunno how to reopen bugs on here, but I think the warning can stay but the comment before the members should be removed.

**Comment by orokro** [comment]
If they aren't static, what technically are variables declared with my, outside of the $self hash?

**Comment by medthehatta** [comment]
I guess they're static members, but it's not really called that in Perl.  It's just in the package scope.

The question is whether you want to implement something analogous to static members in `[insert language here]` using Perl, or if you want to use the Perl-native construct that is closest to static members.

If you want to write Perl-style code, you wouldn't call them static members.  If you want to implement java-style functionality with Perl, you could call them static members.  I guess it's a philosophical difference.  Not totally sure what Classetta's stance is on this.

**Comment by orokro** [comment]
If they behave like static members, then I want to implement them and use the #static comment. It seems like Java's vocabulary is the most common across the different class implementations. Some languages call them "class" variables instead of "static" but it's essentially the same idea. As long as it behaves like a static I'll call it that

**Comment by medthehatta** [comment]
:ok: worksforme
