### ISSUE TITLE
Perl: Notes between =cut and package

### ISSUE THREAD

**Issue by medthehatta** [orokro/Classetta#4]
In the comments section at the beginning, some `#`-style comments are smashed in beneath the POD.  Why not include those comments inside the POD `=begin comment .. =cut`?

```
=begin comment
    Warning! The following Perl code is automatically generated and may contain errors.
[ .. snip .. ]
    Warning! Perl doesn't support Static Methods! Declaring as regular Methods instead.
=cut
# NOTE: Perl doesn't have syntax for definging a class. This code belongs in a file called: "ThoroughDemo.pm".
# ALSO NOTE: Nobody should use Perl for anything, ever.
package ThoroughDemo;

use strict;
use warnings;
```

**Comment by orokro** [comment]
Fixed by overriding the buildCode_Warnings superclass method with a custom one in the perl generator.

**Comment by medthehatta** [comment]
Do the closed bugs have associated checkins?  Or one checkin which fixes multiple issues perhaps?

**Comment by medthehatta** [comment]
Nice
