### ISSUE TITLE
Perl: "All Packages must end in a true statement" comment redundant

### ISSUE THREAD

**Issue by medthehatta** [orokro/Classetta#6]
Perl: "All Packages must end in a true statement" comment redundant
Perl: "All Packages must end in a true statement" comment redundant
Perl: "All Packages must end in a true statement" comment redundant
Perl: "All Packages must end in a true statement" comment redundant
Perl: "All Packages must end in a true statement" comment redundant...

**Comment by orokro** [comment]
Not sure what you mean by this?

The fact that a package must end in a true statement is pretty obscure, and to anyone coming from another language they might wonder what the purpose of 1; is... So I feel like the comment is useful.

**Comment by medthehatta** [comment]
I guess that's true.  Fair enough.
