### ISSUE TITLE
Perl: does not support interfaces, but no warnings

### ISSUE THREAD

**Issue by medthehatta** [orokro/Classetta#7]
There are warnings about Perl not supporting Static Methods, for example, but not warnings that it does not support Interfaces.  Seems warnworthy.

Also, it uses the words "Ancestors and Interfaces" to describe superclasses, which reinforces the support of Interfaces, which shouldn't happen.

**Comment by orokro** [comment]
Commented out the code to list interfaces in @ISA, and removed "interafaces" from the comment. Also added the warning.
